export enum EventBusTypeEnum {
  LOGIN_SUCCESS= 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL',
  LOGOUT = 'LOGOUT',
  INITIAL_STATE = 'INITIAL_STATE',
}
